services:
  relay:
    build: ./relay
    container_name: relay
    ports:
      - "443:443"
    networks:
      - internet

  agent:
    build: ./agent
    container_name: agent
    depends_on:
      - relay
      - web
    networks:
      - internet
      - home

  web:
    image: caddy
    container_name: web
    volumes:
    - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
    - home

networks:
  internet:
  home:
