name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build srp
      run: cargo build --release -p srp
    - name: Build srps
      run: cargo build --release -p srps
    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: rust-binaries
        path: |
          target/release/srp
          target/release/srps
